### ISSUE TITLE
top and down images inverted in cpp

### ISSUE THREAD

**Issue by rickyviking** [madwyn/libcube2cyl#6]
Hi @madwyn,

thanks for the great lib!
I've downloaded the latest version 1.2.1 and used successfully in the c++ flavor. 
Only I had to swap top and down images with respect to your enumeration. 
I had to use image index 0 for the bottom and 5 for the top.
Can you counter check the enumeration usage withing the c++ algorithm?
Thank you,
Ricky

**Comment by madwyn** [comment]
I tested, it worked just fine.
